<?php declare(strict_types=1);

namespace Vizion\Api;

use Base3\Api\IBase;

/**
 * Formats one report field value before it is passed to the grid.
 *
 * Value renderers are discovered by BASE3 ClassMap through getName(). The
 * vdef type must be the same lowercase technical class name. There is no
 * second semantic name layer for value renderers.
 */
interface IReportValueRenderer extends IBase {

	/**
	 * Formats one raw field value for display.
	 *
	 * @param mixed $value Raw value of the configured field alias
	 * @param array<string,mixed> $row Complete row returned by the data query
	 * @param array<string,mixed> $field Original vdef field definition
	 * @param array<string,mixed> $rendererConfig vdef valueRenderer config
	 */
	public function renderValue(mixed $value, array $row, array $field, array $rendererConfig): string;

	/**
	 * True when renderValue() returns trusted HTML generated by the renderer.
	 */
	public function rendersHtml(): bool;
}
